
import React from 'react';
import { Check, AlertTriangle, ShieldAlert } from 'lucide-react';
import { Progress } from "@/components/ui/progress";

interface ResultDisplayProps {
  isAnalyzing: boolean;
  result: {
    prediction: 'real' | 'ai' | null;
    confidence: number;
    details?: {
      realScore: number;
      aiScore: number;
    };
  } | null;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ isAnalyzing, result }) => {
  if (isAnalyzing) {
    return (
      <div className="glassmorphism rounded-xl p-8 w-full max-w-xl mx-auto animate-fade-in">
        <div className="flex flex-col items-center text-center">
          <div className="w-full space-y-2">
            <div className="h-1.5 w-full bg-secondary rounded-full overflow-hidden">
              <div className="h-full bg-primary rounded-full animate-pulse-soft w-3/4"></div>
            </div>
          </div>
          <h3 className="text-lg font-medium mt-4">Analyzing image...</h3>
          <p className="text-muted-foreground text-sm mt-2">
            Our AI is examining the image for signs of artificial generation
          </p>
        </div>
      </div>
    );
  }

  if (!result) return null;

  const { prediction, confidence, details } = result;
  
  return (
    <div className="glassmorphism rounded-xl p-8 w-full max-w-xl mx-auto animate-fade-in">
      <div className="flex flex-col items-center text-center">
        {prediction === 'real' ? (
          <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center mb-4">
            <Check className="text-green-600" size={32} />
          </div>
        ) : prediction === 'ai' ? (
          <div className="w-16 h-16 rounded-full bg-amber-100 flex items-center justify-center mb-4">
            <ShieldAlert className="text-amber-600" size={32} />
          </div>
        ) : (
          <div className="w-16 h-16 rounded-full bg-gray-100 flex items-center justify-center mb-4">
            <AlertTriangle className="text-gray-600" size={32} />
          </div>
        )}

        <h3 className="text-2xl font-semibold mb-2">
          {prediction === 'real' 
            ? 'Real Image' 
            : prediction === 'ai' 
              ? 'AI-Generated' 
              : 'Uncertain Result'}
        </h3>
        
        <p className="text-muted-foreground mb-6">
          {prediction === 'real'
            ? 'This image appears to be a real photograph.'
            : prediction === 'ai'
              ? 'This image appears to be generated by AI.'
              : 'We could not determine if this image is real or AI-generated.'}
        </p>

        <div className="w-full space-y-6">
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span>Confidence</span>
              <span className="font-medium">{Math.round(confidence * 100)}%</span>
            </div>
            <Progress value={confidence * 100} className="h-2" />
          </div>

          {details && (
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span>Real Score</span>
                  <span className="font-medium">{Math.round(details.realScore * 100)}%</span>
                </div>
                <Progress value={details.realScore * 100} className="h-2 bg-secondary" />
              </div>
              
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span>AI Score</span>
                  <span className="font-medium">{Math.round(details.aiScore * 100)}%</span>
                </div>
                <Progress value={details.aiScore * 100} className="h-2 bg-secondary" />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ResultDisplay;
